title: Zhengxi Zhang's Homepage
page-top-title: Zhengxi Zhang
top-section-bg-text: Be what you wanna be
home-subtitle: Zhengxi Zhang&ensp;|&ensp;张正熙
email: 2832489062@qq.com
copyright-text: '&copy; Zhengxi Zhang 2023-2025. All Rights Reserved.'
